[ERROR] Failures: 
[ERROR]   CashSealApprovalServiceTest.findById_repositoryException_throwsSaveException:131 Unexpected exception type thrown ==> expected: <com.ykb.corebanking.vault.money.deposit.withdraw.exception.CashSealApprovalSaveException> but was: <java.lang.RuntimeException>
[INFO] 
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0
